
.PHONY: dist

dev:
	elm-live src/Main.elm --open --start-page dev.html --pushstate -- --output=dist/elm.js

dist: dist/elm.min.js

dist/elm.js:
	elm make src/Main.elm --optimize --output=dist/elm.js

dist/elm.min.js: dist/elm.js
	uglifyjs dist/elm.js --compress 'pure_funcs="F2,F3,F4,F5,F6,F7,F8,F9,A2,A3,A4,A5,A6,A7,A8,A9",pure_getters,keep_fargs=false,unsafe_comps,unsafe' | uglifyjs --mangle --output=dist/elm.min.js
